<?php
/**
 * Robots.txt editor and basic validator.
 *
 * @package Hirany_SEO
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class HSP_Robots {

	/**
	 * Constructor.
	 */
	public function __construct() {
		add_filter( 'robots_txt', array( $this, 'filter_robots_txt' ), 20, 2 );
		add_action( 'hsp_register_admin_pages', array( $this, 'register_admin_page' ) );
	}

	/**
	 * Get robots settings.
	 *
	 * @return array<string,mixed>
	 */
	protected function get_settings() {
		$defaults = array(
			'use_custom' => 0,
			'content'    => '',
		);

		$settings = get_option( 'hsp_robots_settings', array() );

		return wp_parse_args( $settings, $defaults );
	}

	/**
	 * Filter robots.txt output.
	 *
	 * @param string $output Existing output.
	 * @param bool   $public Whether the site is public.
	 * @return string
	 */
	public function filter_robots_txt( $output, $public ) {
		$settings = $this->get_settings();

		if ( empty( $settings['use_custom'] ) ) {
			// Append sitemap hints even when not overriding.
			$extra = $this->build_sitemap_lines();
			if ( $extra ) {
				$output .= "\n" . $extra;
			}
			return $output;
		}

		$content = (string) $settings['content'];

		// Always append sitemap references for convenience.
		$sitemaps = $this->build_sitemap_lines();
		if ( $sitemaps ) {
			$content = trim( $content ) . "\n\n" . $sitemaps;
		}

		/**
		 * Filter the final robots.txt content generated by Hirany SEO.
		 *
		 * @param string $content Robots content.
		 * @param bool   $public  Whether the site is public.
		 */
		return (string) apply_filters( 'hsp_robots_txt_output', $content, $public );
	}

	/**
	 * Build sitemap lines for robots.txt.
	 *
	 * @return string
	 */
	protected function build_sitemap_lines() {
		$lines   = array();
		$home    = home_url( '/' );
		$core    = home_url( '/wp-sitemap.xml' );
		$custom  = home_url( '/hsp-sitemap.xml' );
		$lines[] = 'Sitemap: ' . trailingslashit( $home ) . 'robots.txt';
		$lines[] = 'Sitemap: ' . $core;
		$lines[] = 'Sitemap: ' . $custom;

		return implode( "\n", array_unique( $lines ) );
	}

	/**
	 * Register admin page.
	 *
	 * @param string $parent_slug Parent slug.
	 * @return void
	 */
	public function register_admin_page( $parent_slug ) {
		add_submenu_page(
			$parent_slug,
			__( 'robots.txt', 'hirany-seo' ),
			__( 'robots.txt', 'hirany-seo' ),
			'manage_options',
			HSP_SLUG . '-robots',
			array( $this, 'render_admin_page' )
		);
	}

	/**
	 * Simple robots.txt validator returning warnings.
	 *
	 * @param string $content Content.
	 * @return string[]
	 */
	protected function validate_content( $content ) {
		$warnings = array();
		$lines    = preg_split( '/\r\n|\r|\n/', (string) $content );

		$current_user_agent = '';

		foreach ( $lines as $line ) {
			$trimmed = trim( $line );

			if ( '' === $trimmed || 0 === strpos( $trimmed, '#' ) ) {
				continue;
			}

			if ( preg_match( '/^User-agent:\s*(.+)$/i', $trimmed, $matches ) ) {
				$current_user_agent = trim( $matches[1] );
				continue;
			}

			if ( preg_match( '/^Disallow:\s*(.*)$/i', $trimmed, $matches ) ) {
				$path = trim( $matches[1] );

				if ( '*' === $current_user_agent && '/' === $path ) {
					$warnings[] = __( 'You are disallowing all crawling for all user agents (Disallow: /). This will block your entire site from search engines.', 'hirany-seo' );
				}
			}
		}

		return array_unique( $warnings );
	}

	/**
	 * Render admin page.
	 *
	 * @return void
	 */
	public function render_admin_page() {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		$settings  = $this->get_settings();
		$warnings  = array();
		$test_view = '';

		if ( isset( $_POST['hsp_robots_nonce'] ) && wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['hsp_robots_nonce'] ) ), 'hsp_save_robots' ) ) {
			$use_custom = isset( $_POST['hsp_robots_use_custom'] ) ? 1 : 0;
			$content    = isset( $_POST['hsp_robots_content'] ) ? (string) wp_unslash( $_POST['hsp_robots_content'] ) : '';

			$settings['use_custom'] = $use_custom;
			$settings['content']    = $content;

			update_option( 'hsp_robots_settings', $settings );

			$warnings = $this->validate_content( $content );

			echo '<div class="updated"><p>' . esc_html__( 'robots.txt settings saved.', 'hirany-seo' ) . '</p></div>';
		}

		// Live preview of effective robots.txt.
		$test_view = apply_filters( 'robots_txt', '', '1' );

		?>
		<div class="wrap hsp-wrap">
			<h1><?php esc_html_e( 'robots.txt Editor', 'hirany-seo' ); ?></h1>
			<p>
				<?php
				printf(
					/* translators: %s: robots.txt URL. */
					esc_html__( 'Your robots.txt is served at: %s', 'hirany-seo' ),
					'<code>' . esc_html( home_url( '/robots.txt' ) ) . '</code>'
				);
				?>
			</p>

			<form method="post">
				<?php wp_nonce_field( 'hsp_save_robots', 'hsp_robots_nonce' ); ?>

				<table class="form-table" role="presentation">
					<tr>
						<th scope="row">
							<label for="hsp_robots_use_custom"><?php esc_html_e( 'Override robots.txt', 'hirany-seo' ); ?></label>
						</th>
						<td>
							<input type="checkbox" id="hsp_robots_use_custom" name="hsp_robots_use_custom" value="1" <?php checked( ! empty( $settings['use_custom'] ) ); ?> />
							<span class="description">
								<?php esc_html_e( 'When enabled, Hirany SEO will output this custom content instead of the default WordPress robots.txt.', 'hirany-seo' ); ?>
							</span>
						</td>
					</tr>
					<tr>
						<th scope="row">
							<label for="hsp_robots_content"><?php esc_html_e( 'robots.txt content', 'hirany-seo' ); ?></label>
						</th>
						<td>
							<textarea name="hsp_robots_content" id="hsp_robots_content" rows="12" style="width:100%; font-family:monospace;"><?php echo esc_textarea( (string) $settings['content'] ); ?></textarea>
							<p class="description">
								<?php esc_html_e( 'Edit your robots.txt rules. Warnings will appear below if we detect risky directives such as blocking the entire site.', 'hirany-seo' ); ?>
							</p>
						</td>
					</tr>
				</table>

				<?php submit_button( __( 'Save robots.txt', 'hirany-seo' ) ); ?>
			</form>

			<?php if ( ! empty( $warnings ) ) : ?>
				<div class="notice notice-warning">
					<p><strong><?php esc_html_e( 'Potential issues detected:', 'hirany-seo' ); ?></strong></p>
					<ul>
						<?php foreach ( $warnings as $warning ) : ?>
							<li><?php echo esc_html( $warning ); ?></li>
						<?php endforeach; ?>
					</ul>
				</div>
			<?php endif; ?>

			<h2><?php esc_html_e( 'Effective robots.txt Preview', 'hirany-seo' ); ?></h2>
			<pre style="background:#fff;border:1px solid #ccd0d4;padding:10px;max-height:260px;overflow:auto;"><?php echo esc_html( $test_view ); ?></pre>
		</div>
		<?php
	}
}

