<?php
/**
 * llms.txt generator and endpoint.
 *
 * @package Hirany_SEO
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class HSP_Llms {

	/**
	 * Constructor.
	 */
	public function __construct() {
		add_action( 'init', array( $this, 'register_rewrites' ) );
		add_filter( 'query_vars', array( $this, 'register_query_vars' ) );
		add_action( 'template_redirect', array( $this, 'handle_request' ) );
		add_action( 'hsp_register_admin_pages', array( $this, 'register_admin_page' ) );
	}

	/**
	 * Install hook.
	 *
	 * @return void
	 */
	public function install() {
		$this->register_rewrites();
		flush_rewrite_rules();
	}

	/**
	 * Register rewrite rule for llms.txt.
	 *
	 * @return void
	 */
	public function register_rewrites() {
		add_rewrite_rule( '^llms\.txt$', 'index.php?hsp_llms_txt=1', 'top' );
	}

	/**
	 * Register query vars.
	 *
	 * @param string[] $vars Vars.
	 * @return string[]
	 */
	public function register_query_vars( $vars ) {
		$vars[] = 'hsp_llms_txt';
		return $vars;
	}

	/**
	 * Get current llms.txt content.
	 *
	 * @return string
	 */
	protected function get_content() {
		$default = implode(
			"\n",
			array(
				'# llms.txt generated by Hirany SEO',
				'# This file helps AI search engines discover your most important content.',
				'Host: ' . home_url( '/' ),
				'Sitemap: ' . home_url( '/hsp-sitemap.xml' ),
				'Allow: /',
			)
		);

		/**
		 * Filter default llms.txt content.
		 *
		 * @param string $default Default content.
		 */
		$default = apply_filters( 'hsp_llms_txt_default', $default );

		$content = get_option( 'hsp_llms_txt_content', '' );

		return $content ? (string) $content : $default;
	}

	/**
	 * Handle llms.txt request.
	 *
	 * @return void
	 */
	public function handle_request() {
		if ( ! get_query_var( 'hsp_llms_txt' ) ) {
			return;
		}

		$content = $this->get_content();

		nocache_headers();
		header( 'Content-Type: text/plain; charset=' . get_bloginfo( 'charset' ), true );
		echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		exit;
	}

	/**
	 * Register llms.txt admin page.
	 *
	 * @param string $parent_slug Parent slug.
	 * @return void
	 */
	public function register_admin_page( $parent_slug ) {
		add_submenu_page(
			$parent_slug,
			__( 'llms.txt', 'hirany-seo' ),
			__( 'llms.txt', 'hirany-seo' ),
			'manage_options',
			HSP_SLUG . '-llms',
			array( $this, 'render_admin_page' )
		);
	}

	/**
	 * Render llms.txt editor.
	 *
	 * @return void
	 */
	public function render_admin_page() {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		if ( isset( $_POST['hsp_llms_nonce'] ) && wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['hsp_llms_nonce'] ) ), 'hsp_save_llms' ) ) {
			if ( isset( $_POST['hsp_llms_reset'] ) ) {
				delete_option( 'hsp_llms_txt_content' );
				$content = $this->get_content();
				echo '<div class="updated"><p>' . esc_html__( 'llms.txt reset to default.', 'hirany-seo' ) . '</p></div>';
			} else {
				$content = isset( $_POST['hsp_llms_content'] ) ? wp_unslash( $_POST['hsp_llms_content'] ) : '';
				$content = (string) $content;
				update_option( 'hsp_llms_txt_content', $content );
				echo '<div class="updated"><p>' . esc_html__( 'llms.txt updated.', 'hirany-seo' ) . '</p></div>';
			}
		}

		$content = $this->get_content();
		?>
		<div class="wrap hsp-wrap">
			<h1><?php esc_html_e( 'llms.txt Editor', 'hirany-seo' ); ?></h1>
			<p>
				<?php
				printf(
					/* translators: %s: llms.txt URL. */
					esc_html__( 'Your llms.txt is available at: %s', 'hirany-seo' ),
					'<code>' . esc_html( home_url( '/llms.txt' ) ) . '</code>'
				);
				?>
			</p>
			<form method="post">
				<?php wp_nonce_field( 'hsp_save_llms', 'hsp_llms_nonce' ); ?>
				<textarea name="hsp_llms_content" id="hsp_llms_content" rows="12" style="width:100%; font-family: monospace;"><?php echo esc_textarea( $content ); ?></textarea>
				<p class="description">
					<?php esc_html_e( 'Customize the content of your llms.txt file. AI search engines may use this file to understand which sections of your site are most important or any crawl preferences.', 'hirany-seo' ); ?>
				</p>
				<?php submit_button( __( 'Save llms.txt', 'hirany-seo' ) ); ?>
				<?php submit_button( __( 'Reset to default', 'hirany-seo' ), 'secondary', 'hsp_llms_reset', false ); ?>
			</form>
		</div>
		<?php
	}
}

